### ISSUE TITLE
Why use 3 optimizers during training?

### ISSUE THREAD

**Issue by Ther-nullptr** [princeton-nlp/CoFiPruning#17]
Hi! I want to ask why we should use 3 optimizers during training? I think `self.optimizer.zero_grad()` is enough.
```python
self.optimizer.zero_grad()
if self.l0_optimizer is not None:
     self.l0_optimizer.zero_grad()
if self.lagrangian_optimizer is not None:
     self.lagrangian_optimizer.zero_grad()
```

**Comment by xiamengzhou** [comment]
These three optimizers are used to update the parameters of different model parts. `self.optimizer` is used to update the main model parameters; `self.l0_optimizer` is used to update the parameters of the L0 module and `self.lagrangian_optimizer` is used to update the lagrangian parameters (\lambda_1 and \lambda_2). The learning rates used for these optimizers are different.

**Comment by Ther-nullptr** [comment]
get it!
