### ISSUE TITLE
Pruning for Encoder-Decoder Architecture?

### ISSUE THREAD

**Issue by Luckick** [princeton-nlp/CoFiPruning#19]
Hi,
Does CoFiPruning work on Encoder-Decoder Architectures for Seq2seq tasks such as translation?
Thanks!

**Comment by xiamengzhou** [comment]
Hi,

Thanks for your interest in our repository. Unfortunately, the current version does not support seq2seq models yet. But technically the approach could be adapted to seq2seq models. I'd be happy to help if you have any issues implementing it!

**Comment by Luckick** [comment]
Does the pruning technique work only for encoder layers or both encoder and decoder layers?

**Comment by xiamengzhou** [comment]
It should work for both but would require placing the masking variables on the decoder side and cross-attentions properly.

**Comment by Luckick** [comment]
Thank you for the clarification and help!
