### ISSUE TITLE
Obtaining models having different target sparsity using single trained model

### ISSUE THREAD

**Issue by chamecall** [princeton-nlp/CoFiPruning#2]
Hello. 
First of all thanks for your great work.
I have the following question. 
If we trained a model having for example ~90% target sparsity is it possible to get variations of the already trained model with decreasing sparsity like 75%, 50% etc or the only way to obtain different target sparsity is to retrain the model again with needed sparsity?
Thanks in advance`)

**Comment by xiamengzhou** [comment]
Hi, 

CoFi requires training a single model every time for a specific sparsity. But given a lower sparsity model, e.g., 75%, you can load the model and the l0_module back and reset the target sparsity to be a higher number, e.g. 90% and keep training with the pruning objective to get a 90% sparsity model. I never tried this but it should require a minimal change to the codebase to make it work.
