### ISSUE TITLE
About the upper layer in your paper

### ISSUE THREAD

**Issue by CaffreyR** [princeton-nlp/CoFiPruning#24]
Hi @xiamengzhou , many thanks to your contribution. I have a small question in your paper, in your paper you said that 

> CoFi tends to prune submodules more from upper layers than lower layers.

What is the upper layer means? Is it near input or output? Many thanks!
<img width="442" alt="image" src="https://user-images.githubusercontent.com/84232793/189467678-0bfaf7e7-27ed-4564-aef7-c4a0a4b0d0fb.png">

**Comment by xiamengzhou** [comment]
Upper layers mean the layers that are closer to the output!

**Comment by CaffreyR** [comment]
Many thanks! :)
