### ISSUE TITLE
training error about qnli

### ISSUE THREAD

**Issue by iMountTai** [princeton-nlp/CoFiPruning#27]
Great job. However, when I train to the 3rd epoch in the QNLI task, I encounter the following problem, but the CoLA or Squad tasks do not encounter this problem. Do you have any suggestions? I will be very grateful!

![image](https://user-images.githubusercontent.com/35353688/195260801-c7e44fef-57db-403e-b834-67f1e71d3505.png)
The error may appear in the following code block
in the file: https://github.com/princeton-nlp/CoFiPruning/blob/main/trainer/trainer.py,Lines 680-685
```
lagrangian_loss = None
if self.start_prune:
        lagrangian_loss, _, _ = \
                 self.l0_module.lagrangian_regularization(
                        self.global_step - self.prepruning_finetune_steps)
        loss += lagrangian_loss
```

**Comment by horizon86** [comment]
Hello, I met the same error on my own code but not CoFi. You can set CUDA_LAUNCH_BLOCKING=1 to get more stacktrace to help debug :smile:

**Comment by iMountTai** [comment]
When layer_distill_version=3 no longer reports an error, it may be that some layers are lost.But another problem arises, when I fine-tune, the following code needs to be changed
![image](https://user-images.githubusercontent.com/35353688/195544730-cc72beb6-ef90-48eb-b201-a9e7dd5bc653.png)
is this correct?

**Comment by xiamengzhou** [comment]
Which `layer_distill_version` did you use when you encountered the error? Sorry for the late reply, I am happy to help with debugging!

**Comment by iMountTai** [comment]
layer_distill_version=4,Now the problem is solved, thank you!
