### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by iMountTai** [princeton-nlp/CoFiPruning#29]
Hello,@xiamengzhou !The result on the Squad task dataset is 79.74, which is quite different from the result (82.6) in the paper. Can you further announce the detailed parameters? The teacher model F1 value is 88.43. I will be very grateful!

**Comment by xiamengzhou** [comment]
Hi, 

A few details are worth looking at for SQuAD:

- We reported results of a 92.4% sparsity for SQuAD, as shown in `README.md`, pruning it to 95% would lead to a `1-2` points drop.
- Make sure that you finetune the model after finalizing the structure! It makes a huge difference for highly pruned models. 

Let me know if you have more questions!

**Comment by iMountTai** [comment]
Thanks!
