### ISSUE TITLE
Generating predictions with CoFi models

### ISSUE THREAD

**Issue by eldarkurtic** [princeton-nlp/CoFiPruning#37]
Hi,
First of all, thanks a lot for open-sourcing your code and models!

I've been trying to use your code to generate predictions with CoFi models (with `--do_predict` on for example test-split of GLUE tasks) but unfortunately the prediction loop always fails with CUDA OOM exception (even on the 80GB A100 GPU). Could you also please try and let me know if I did something wrong?

**Comment by xiamengzhou** [comment]
Hi, sorry for the late reply! Which script are you using exactly? Could you provide the command line?

**Comment by eldarkurtic** [comment]
Hey, no worries at all, it was a problem on my side. Sorry for spamming, and btw, really cool work! :-)
