### ISSUE TITLE
Detailed experiment results on RoBERTa?

### ISSUE THREAD

**Issue by ROIM1998** [princeton-nlp/CoFiPruning#48]
Hello! Appreciate your great work. In the appendix of your paper, I saw figures illustrating the experiment results of applying CoFi on RoBERTa, but I cannot reproduce the results based on this repository.  Could you please provide more detailed experimental results? Thanks!

**Comment by xiamengzhou** [comment]
Hi, thanks for working with our repo! please find the numerical results of CoFi on Roberta [here](https://docs.google.com/spreadsheets/d/1IF6ReWkSDKnZomvQT9GBlEhfN48NoDyr-XHOvD2vjvs/edit#gid=0). Unfortunately, we ran minimal experiments with Roberta at the time and could not provide more results.

**Comment by ROIM1998** [comment]
Thanks for your reply! This really helps a lot.
