### ISSUE TITLE
Bug or intent?

### ISSUE THREAD

**Issue by mpiorczynski** [princeton-nlp/CoFiPruning#53]
Hi! I have a question, why are you checking if the MHA layer is not pruned in [this line](https://github.com/princeton-nlp/CoFiPruning/blob/da855a809c4a15e1c964a47a37998db2e1a226fd/trainer/trainer.py#L604), unlike [here](https://github.com/princeton-nlp/CoFiPruning/blob/da855a809c4a15e1c964a47a37998db2e1a226fd/trainer/trainer.py#L570) where you check for the FFN layer? Since distillation happens at the outputs of FFN layers, shouldn't the check be for the presence of FFN instead of MHA? Is this intentional or potentially a bug?

**Comment by xiamengzhou** [comment]
It seems to be a bug to me. The correct way to define existing layers should be `existing_layers = (head_layer_z != 0) | (mlp_z != 0)`. We mostly used version 3 during our development and didn't test version 4 much. Thanks for pointing this out!

**Comment by mpiorczynski** [comment]
Thanks a lot!
