### ISSUE TITLE
prunable_model_size updated only in initialize_structured_head

### ISSUE THREAD

**Issue by tatami-galaxy** [princeton-nlp/CoFiPruning#54]
Hi this is a clarification question. In [l0_module.py](https://github.com/princeton-nlp/CoFiPruning/blob/main/models/l0_module.py) `self.prunable_model_size` is updated only in the [initialize_structured_head](https://github.com/princeton-nlp/CoFiPruning/blob/main/models/l0_module.py#L121) function but not in either [initialize_structured_mlp](https://github.com/princeton-nlp/CoFiPruning/blob/main/models/l0_module.py#L140) or in [initialize_whole_mlp](https://github.com/princeton-nlp/CoFiPruning/blob/main/models/l0_module.py#L151). Why is that? The mlp layers can also be pruned later I believe?

**Comment by xiamengzhou** [comment]
Hi! The `prunable_model_size` is updated in both `initialize_structured_head` and `initialize_structured_mlp`, as the parameters these two substructures govern overlap with the ones in `initialize_whole_mlp` and `initialized_layer_structured_heads`, they are not updated in the latter two functions.

**Comment by tatami-galaxy** [comment]
My apologies. I missed the line where `prunable_model_size` is being updated in `initialize_structured_mlp`. Thanks a lot for the quick response.
