### ISSUE TITLE
About  prepruning finetune steps

### ISSUE THREAD

**Issue by backspacetg** [princeton-nlp/CoFiPruning#9]
Thank you for your amazing work!

I have some difficulty understanding the pre-pruning fine-tune steps in the code.   I found that in pre-pruning fine-tune steps, only layer and prediction distillation losses are calculated, but it seems that the teacher and student models are both bert-base models. Does this mean that the distillation is between two same models? If so, why should we do that?

**Comment by xiamengzhou** [comment]
Hi, 

Sorry for getting back to you late! The pre-pruning fine-tuning step is to distill a finetuned BERT model to a pre-trained BERT model. Let me know if you have more questions!

**Comment by backspacetg** [comment]
Oh I see! Thanks for your reply!

**Comment by mpiorczynski** [comment]
Hi, I have a question about the intuition behind this step. Why are you not initializing the student model from the teacher weights, instead of initializing it from scratch (/pretrained on MLM BERT checkpoint)?
